### ISSUE TITLE
Suggestion: namedtuples for entries

### ISSUE THREAD

**Issue by evanmiltenburg** [timmahrt/praatIO#1]
Thanks for creating this library. I've a suggestion for improvement: use named tuples for entries rather than plain tuples. Here's an example:

    from collections import namedtuple
    Entry = namedtuple('Entry', ['start', 'end', 'label'])
    
    # Example
    entry = Entry(0.0, 0.30, 'sound')
    print(entry)

Result: `Entry(start=0.0, end=0.3, label='sound')`

The nice thing about this is that you don't have to do any indexing anymore, but you can just do `entry.start` to get the starting time.

**Comment by timmahrt** [comment]
How have I never heard of named tuples before?  What a great idea.

I've added this functionality to version 3.6.7.  Entries can now have their contents access via index or via labels, as you suggested

Interval Tier entries:
entry[0] <=> entry.start
entry[1] <=> entry.end
entry[2] <=> entry.label

Point Tier entries:
entry[0] <=> entry.time
entry[1] <=> entry.label

Thanks for the great suggestion!

**Comment by evanmiltenburg** [comment]
Cool, thanks for implementing this!
