### ISSUE TITLE
README code outdated and misleading

### ISSUE THREAD

**Issue by William-N-Havard** [timmahrt/praatIO#10]
The code snippets provided on the README is outdated and misleading. 

For example, it is written that the method "openTextGrid" should be used when the true name of the method is "openTextgrid".

**Comment by timmahrt** [comment]
I just noticed this with another of my projects.  I'll go through all my readme files this week and make sure they're up to date.  Sorry for the inconvenience.

**Comment by William-N-Havard** [comment]
Thanks!

**Comment by timmahrt** [comment]
Done!  It was more out-of-date than I thought.  Thanks again!
