### ISSUE TITLE
Forced alignment?

### ISSUE THREAD

**Issue by Terrance82** [timmahrt/praatIO#11]
Hi, 

I've studied a little bit of forced alignment so currently I have a wav file which spoke "hello" and a .txt file which contain the word "hello". Can I use some sort of forced alignment to find out where is the start or end of the sentences along with its pronunciation? 
If so is it possible to do it in a Window 10 OS?

Thank you.

**Comment by timmahrt** [comment]
Hi, That is exactly what forced alignment is for.  Check out the program
called sppas:
http://www.sppas.org/

It works for English and on Windows.

**Comment by Terrance82** [comment]
Thank you for the great resource.
I was thinking if there is a script that combines tokenization and phonetization and generate a TextGrid file that output to this by using wav file and the txt file:
![image](https://user-images.githubusercontent.com/46440484/51300932-78602a80-1a68-11e9-87da-ab5a5e47a807.png)

**Comment by timmahrt** [comment]
SPPAS has an API that you could use to write a script.  It does
tokenization and phonetization.  It works for several European languages.

I have a project, pyJuliusAlign, that will do what you are looking for.  It
works with Japanese and is also available on my github page.

What language is your data in?

**Comment by Terrance82** [comment]
Oh thank you! 
My data is in english. Could you recall the name of the api?

**Comment by timmahrt** [comment]
The program I mentioned earlier SPPAS has both a UI and a python API.

Here is a reference guide.  Scroll down about half way to get the SPPAS
specific instructions:
http://www.sppas.org/documentation_06_scripting.html

**Comment by timmahrt** [comment]
This issue has been inactive so I'm closing it.  If you have more questions, please feel free to reopen it.

**Comment by kavyabgowda** [comment]
Hi,

I have Audio files of conversation of about 10minutes with 3 participants. But, my transcript involves only one speaker and I need to force align these transcripts with the audio files. My audio files are in English. May I know the forced aligner CLI tool for this case.

Thanks

**Comment by timmahrt** [comment]
Hi,
I recommend you look into SPPAS--the tool discussed above--I think it will cover your needs.

If you don't want to use that you could also try 
https://github.com/prosodylab/Prosodylab-Aligner
