### ISSUE TITLE
can i save a normal textgrid but not a short textgrid using praatIO

### ISSUE THREAD

**Issue by dfdjoker** [timmahrt/praatIO#15]
Hi,timmahrt:
   I want to save textgrid using praatio,but I found that it save as a short textgrid.Can I save a normal textgrid?

**Comment by timmahrt** [comment]
praatIO currently does not have the capacity to save a normal textgrid.  It shouldn't be difficult to add. 
 I'm a bit busy at the moment but will try to have it out sometime this week.

**Comment by timmahrt** [comment]
Hello dfdjoker,
I have just released Praatio 3.8.0 which has the ability to save in the Textgrid long file format.  By default, it will still save to the short file format.

You can save a long Textgrid file like so:
```
tg.save(fn, useShortForm=False)
```

If you have any feedback, please let me know.  If you're satisfied, please close the issue.
Thanks!
Tim

**Comment by dfdjoker** [comment]
Thank you so much!
