### ISSUE TITLE
xsampa.py lack of license

### ISSUE THREAD

**Issue by toddrme2178** [timmahrt/praatIO#16]
`praatio/utilities/xsampa.py` is listed as "does not carry any license".  IANAL, but my understanding is that without any license, no one has permission to use it.  It may be included in the source of the project with permission, but without an explicit license for the file no one else can know exactly how they are allowed to use it, if at all.  Is there any way to contact the author and get a specific license for the file, such as MIT like the main project?

**Comment by timmahrt** [comment]
I originally wrote to the author asking about including it in my repository and he replied: "Feel free to use [my library] anyway you like."  

I didn't think there would be legal problems beyond that.  You are not the first person to raise this concern.  I'll contact him again and see if its ok if I include it under the MIT or other open source license.

I hope to get back to you soon.

Thanks!

**Comment by timmahrt** [comment]
@toddrme2178 I've received permission from the author to include his library as open source under the MIT license.

However, on thinking more about it, is receiving email permission enough?  If people visit the author's page, they'll see that non of his work carries any license.  

His code is not a core feature of praatio.  I would be ok with not including the code if its not a good practice.

**Comment by timmahrt** [comment]
I've decided to remove the unlicensed code.  I'm not sure when I'll have time to sit down and do so but hopefully soon.

**Comment by toddrme2178** [comment]
@timmahrt Sorry, I am not a lawyer.  I really don't know what would be considered sufficient in this case.  Removing it is probably safe if we doesn't want to put either a license on his site or a new version of the file with a license in the file itself.  If he wants other people to use his code then providing a license would facilitate that, but that is up to him.

**Comment by timmahrt** [comment]
@toddrme2178 I've scrubbed xsampa from my code base, including all of the related examples and utility code I had written for it.

I won't be including unlicensed code in my repos going forward.  Thank you for the push 🙇

**Comment by timmahrt** [comment]
If its ok, I'll close this issue.  All of the unlicensed code has been removed.

Please feel free to open it for further discussion.
