### ISSUE TITLE
No tag for 3.8.1

### ISSUE THREAD

**Issue by toddrme2178** [timmahrt/praatIO#17]
Version 3.8.1 is released, but there is no tag on github.  Would it be possible to add a tag for it?

Tags are useful for downstreams since they let them get the full, exact upstream source, unlike sdists which only have some of the files.  In this case, in particular the github tags include the tests while sdists don't.

**Comment by timmahrt** [comment]
Sorry, that was oversight on my part.  I've added the tag.  Thanks!
