### ISSUE TITLE
Montreal Forced Aligner compatability

### ISSUE THREAD

**Issue by nrgslp** [timmahrt/praatIO#23]
I have found that `useShortForm=False` must be set in tg.save() in order for the TextGrids to be readable by the Montreal Forced Aligner. This knowledge may be helpful for other users.

**Comment by timmahrt** [comment]
Thanks for reporting this issue!  It could be a bug in praatio.

I am not familiar with the Montreal Forced Aligner.  Can you try to save a short form text grid in praat and open it in the Montreal Forced Aligner?  If it works ok, then praatio has a bug.  If it does not work, then the Montreal Forced Aligner only accepts the full length text grids and they should update their code or their documentation.

https://www.fon.hum.uva.nl/praat/manual/TextGrid_file_formats.html
![Screen Shot 2021-01-15 at 10 20 37 AM](https://user-images.githubusercontent.com/2650064/104668533-9d510c00-571b-11eb-803b-d59d7fc9eaa5.png)

**Comment by nrgslp** [comment]
Thanks for the response. TGs that were once readable by the MFA are no longer readable after saving as a short text file. I will follow up with the MFA team.

**Comment by timmahrt** [comment]
Thank you!  I'm sorry for the hassle.  If there is anything else I can help with, please let me know.

I'll close this issue for now, but if you have any more questions, feel free to reopen it.
