### ISSUE TITLE
Textgrid validation

### ISSUE THREAD

**Issue by timmahrt** [timmahrt/praatIO#26]
A user might make certain assumptions about their data and praatio will silently break those expectations. It can make calculation errors go unnoticed.

Scenario A
- Textgrid A has a maxTimestamp of 10.12345
- Textgrid B has a maxTimestamp of 10.123456
- both textgrids have an intervalTier with a final entry that runs to the end of the file
- if those Textgrids are combined (using append) the interval in Textgrid A will no longer run to the new end of the file, although that may have been the original intention 

Scenario B?

Solution?
- validate on save will probably be too late for Scenario A but can be caught when adding the tier to the Textgrid
- validation could potentially be desired anywhere (will this pollute function signatures more?  Is there a cleaner way to do this?)
- only offer validation in "risky" functions?  Some functions already have the option to throw exceptions if unexpected data is encountered
- to what extent is it the users responsibility to validate and to what extent is it praatios?

**Comment by timmahrt** [comment]
Adding a parameter to addTier to enforce lengths could be prblematic because its used in a lot of places.

What about a "safety" mode set on the Textgrid.  If turned on, some operations will throw errors?  Although that sounds kindof vague and hard to understand for the user about when or when something is or is not being validated.

**Comment by GalaxieT** [comment]
How about just show warnings and info about it, instead of interrupting the process?

**Comment by timmahrt** [comment]
I could imagine all three scenarios would be useful in different cases: silence, warn, exit.

**Comment by timmahrt** [comment]
I'm getting closish to a release.  Praatio 5.0 will feature Textgrid validation.  Users will have a choice to to silently ignore errors, print to the screen (default behavior), or to stop execution on errors.

Wholistic validation is done on save but more narrow validation is done when automatic "unexpected" behavior might occur, such as when adding new entries to a tier or when adding a tier to a textgrid.
https://github.com/timmahrt/praatIO/pull/28

I still need to write lots of tests and update the documentation--I'm going to aim to have it done in a week or two.

**Comment by GalaxieT** [comment]
That's very nice!

**Comment by timmahrt** [comment]
Praatio 5.0 is now released. As with my previous comment functions that may result in automatic "unexpected" behavior take a flag to either silently change, change and print a warning, or throw an exception.

**Comment by GalaxieT** [comment]
Nevermind, and the new release looks amazing!
