### ISSUE TITLE
PraatIO on conda-forge

### ISSUE THREAD

**Issue by mmcauliffe** [timmahrt/praatIO#33]
Hi Tim, I added praatio to conda-forge as that was the one dependency that wasn't on there, the feedstock is here: https://github.com/conda-forge/praatio-feedstock.  Would you like me to add you as a maintainer?  I'm happy to keep it up to date as necessary for MFA as well.

**Comment by timmahrt** [comment]
It seems like an unnecessary burden on you to maintain praatio-feedstock on conda forge, but I leave the decision to you.

If you add me as a maintainer, I'll try to keep it in sync with praatio

**Comment by mmcauliffe** [comment]
Ok, added you!

**Comment by timmahrt** [comment]
Thank you!
