### ISSUE TITLE
Potential bug in `audio.extractSubwav` and/or `audio.openAudioFile`

### ISSUE THREAD

**Issue by scottmk** [timmahrt/praatIO#38]
[`audio.extractSubwav` calls `audio.openAudioFile`](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L78-L86) with a `keepList` containing `startT` and `endT` and no `deleteList`:

```python
def extractSubwav(fn: str, outputFN: str, startT: float, endT: float) -> None:
    audioObj = openAudioFile(
        fn,
        [
            (startT, endT, ""),
        ],
        doShrink=True,
    )
    audioObj.save(outputFN)
```

[In `audio.openAudioFile` L491](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L488-L492), it calls `utils.invertIntervalList` with `duration` given as the `min`:

```python
elif deleteList is None and keepList is not None:
        computedKeepList = []
        computedDeleteList = utils.invertIntervalList(
            [(start, end) for start, end, _ in keepList], duration
        )
```

In this case, the `computedDeleteList` will always be empty, because the `min` time provided is the end of the original wav file.

This means when you call `audio.extractSubwav`, you will always get an empty result.

To further complicate things, even if you changed [L491](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L491) to specify `min=0, max=duration`, you'll still get an empty result for `audio.extractSubwav`.

This is because on [L489](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L489), it sets `computedKeepList = []`, and then on [L499, the original `keepList`](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L499) is overridden with the now empty `computedKeepList`:

```python
keepList = [(row[0], row[1], _KEEP) for row in computedKeepList]
```

Finally, when we actually do the operations, because [`audio.extractSubwav` calls `audio.openAudioFile` with `doShrink=True`](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L84), it won't actually delete anything on [LL519-521](https://github.com/timmahrt/praatIO/blame/50dbff6efb33a93c675d993b6deb08505e45e094/praatio/audio.py#L519-L521):
```python
        elif label == _DELETE and doShrink is False:
            zeroPadding = [0] * int(framerate * diff)
            audioSampleList.extend(zeroPadding)
```

And it won't keep anything because `keepList` is empty.

**Comment by scottmk** [comment]
I think there are two things that should happen to fix this:

1. The `elif` on LL488-492 should be split into two `elif`s: one where `doShrink` is `True`, and one where it is `False
2. The call to `audio.openAudioFile` on L491 should be changed to set `min=0, max=duration`

```python
    elif deleteList is None and keepList is not None and not doShrink:
        computedKeepList = []
        computedDeleteList = utils.invertIntervalList(
            [(start, end) for start, end, _ in keepList], min=0, max=duration
        )
    elif deleteList is None and keepList is not None:
        computedKeepList = keepList
        computedDeleteList = []
```

I tested this locally by calling `audio.extractSubwav`, and I got the desired result. Obviously this would need to be tested against other cases.

I'm happy to submit a PR for this if that helps.

**Comment by timmahrt** [comment]
Thank you for the detailed explanation!  I will take a look at this this week.  Thank you!

**Comment by scottmk** [comment]
Of course! If I can help, please let me know! And thanks for releasing this. You saved me a ton of time and effort.

**Comment by timmahrt** [comment]
Sorry for the lack of updates.  Life happens but this is still on my todo list.  🙈

**Comment by scottmk** [comment]
> Sorry for the lack of updates. Life happens but this is still on my todo list. 🙈

No worries at all! I totally understand and relate. I may post a few other issues as I come across them, but it's mostly just to document them. Just want to give back a little to a project that helped me a ton! 🙏

**Comment by timmahrt** [comment]
Thank you again for the feedback.  I investigated and agree that the fix you proposed would solve the issue.

However, while investigating, I found another bug. I fixed that bug and then started cleaning up the code. I might have got carried away.  I have a PR up but still need to at least write tests. I might do some more tinkering too:
https://github.com/timmahrt/praatIO/pull/41

**Comment by timmahrt** [comment]
The bugfixes to `audio.py` are now released in praatio 6.0. Sorry again for the delay. 🙇

**Comment by scottmk** [comment]
No need to apologize! I really appreciate all the work you've put into this. This software has been immensely valuable to me in my research.

**Comment by timmahrt** [comment]
I will close this issue for now.  If there are related issues, feel free to reopen this!  🙇
