### ISSUE TITLE
use praat to segment a speech file

### ISSUE THREAD

**Issue by bhomass** [timmahrt/praatIO#5]
Hi I am very new to Praat overall, not just the python version. 

is Praat a good tool to use to segment a .wav file if I know the exact times marks where I want to chop up the file? I like to just use Praat, because afterwards I will be extracting pitch and tempo from the segments.

**Comment by timmahrt** [comment]
Hello Bruce,
If you already know the times that you want to mark, you should write a
script that generates the transcription file (.textgrid).  Do you have a
csv file or rule (eg every 0.5 seconds) of when you want to annotate?  It
would only take a small script to generate textgrids from it.

For manually annotating an audiofile with visual inspection of a
spectrogram and waveform, I don't know of a better tool than praat.

If you're making coarse measurements, (like for film) there might be better
tools.  Elan is popular for sociolinguistic and discourse-level annotations
and for making annotations for speech that includes video recording.

**Comment by bhomass** [comment]
Thank you Tim. What if I want the output to be small wav files instead of transcription files? Another word, as the intermedia form, I want sound files for each speaker / utterance, then I will apply additional Praat processing on each segment.

**Comment by timmahrt** [comment]
Hello Bruce,
If you know where you want to extract or segment the audio file, getting
the subwav files is easy.

Accuracy could be lower for some measurements however.  For example,
praat's pitch algorithm uses contextual information in determining the
pitch contour.  It will take longer to extract pitch for a long wave file
but will lead to higher quality results than if you extract individual
words and analyze the pitch for them individually.

It all depends on what your data is like and what you want the final output
to be.

Tim

**Comment by bhomass** [comment]
I am looking at the extract_subwavs.py example. what does "Extracts a separate wav file for each tier in a textgrid" mean? isn't the wav behind each tier always the same? Each tier just highlights different attributes of the same underlying audio stream.

**Comment by timmahrt** [comment]
I'm away from a computer at the moment but I would imagine I meant
"extracts a subwave for each entry in a given tier of a textgrid"

I'll confirm later when I can look at the code.

**Comment by bhomass** [comment]
yes, I see this in the script comment:
Outputs one subwav for each entry in the tier of a textgrid

**Comment by bhomass** [comment]
I successfully segmented a long wav file by time mark. Thank you very much!

**Comment by timmahrt** [comment]
Awesome!  Let me know if you need anything else.

Good luck!
