### ISSUE TITLE
Did there any incompatible upgrade in parratio==6.0.0  Textgrid' object has no attribute 'tierDict'

### ISSUE THREAD

**Issue by yt605155624** [timmahrt/praatIO#54]
This problem occured when parratio==6.0.0
```bash
Textgrid' object has no attribute 'tierDict'
```

**Comment by yt605155624** [comment]
oh, I find this https://github.com/timmahrt/praatIO/blob/main/UPGRADING.md#version-5-to-6-migration

**Comment by timmahrt** [comment]
Sorry for the hassle. Please let me know if you have any difficulty upgrading!

**Comment by yt605155624** [comment]
Thx，I just fix praatio's version >=5.0.0,<=5.1.1，by the way， there are  also incompatible upgrade in praatio 4-> 
5，and you have reported this to me in PaddlePaddle/Parakeet at that time.😃

**Comment by timmahrt** [comment]
I'll close this for now, but if there are any related issues, feel free to reopen.

Version 7 might come out this year, but we'll see!  🙇
