### ISSUE TITLE
Incorrect Error Message /praatio/data_classes/interval_tier.py line 99

### ISSUE THREAD

**Issue by johannahom** [timmahrt/praatIO#56]
Hi there,

Very nice package. I just noticed one of the error messages is not informative for when intervals overlap. It prints out only one of the intervals twice:

`       for entry, nextEntry in zip(self.entries[0::], self.entries[1::]):
            if entry.end > nextEntry.start:
                raise errors.TextgridStateError(
                    "Two intervals in the same tier overlap in time:\n"
                    f"({entry.start}, {entry.end}, {entry.label}) and ({entry.start}, {entry.end}, {entry.label})"
                )
`

Should read:

`        for entry, nextEntry in zip(self.entries[0::], self.entries[1::]):
            if entry.end > nextEntry.start:
                raise errors.TextgridStateError(
                    "Two intervals in the same tier overlap in time:\n"
                    f"({entry.start}, {entry.end}, {entry.label}) and ({nextEntry.start}, {nextEntry.end}, {nextEntry.label})"
                )
`

**Comment by timmahrt** [comment]
I'll close this issue for now. If you have related issues, feel free to reopen it.  Thank you!
