### ISSUE TITLE
visualize textGrid

### ISSUE THREAD

**Issue by bhomass** [timmahrt/praatIO#6]
Hi I have been reading thru the tutorial for a while now. There are two very nice displays showing these textGrid tiers, but I don't see any sample code for creating these png's, or display them by any other means. How are the visualization images generated?

**Comment by timmahrt** [comment]
I'm pretty sure those are cleaned-up screenshots.  Praat has a drawing
mechanism that can be used to programmatically show textgrids and
spectrograms but I'm not familar with it.

I've used matplotlib in python to plot graphs as pngs, but not for
spectograms or textgrids.

**Comment by timmahrt** [comment]
This issue has been inactive so I'm closing it.  If you have more questions, please feel free to reopen it.
