### ISSUE TITLE
Extracting out the phoneme / phone from audio

### ISSUE THREAD

**Issue by jiunn95** [timmahrt/praatIO#8]
Hi Tim,

You've explained how to create a blank textgrid from audio file in your tutorial. I was wondering how do you extract out the (phoneme / phone) and words from audio and insert into textgrid.

Thank you!

**Comment by jiunn95** [comment]
So after I extracted out the phoneme I perform a forced aligners with the text I had. But how do we add into the tiersdict along with the entryList like the example:
['phone', 'word']
Inside the word is ['mary', 'rolled', 'the', 'barrel']

**Comment by jiunn95** [comment]
Specifically how do you add a new tier for example 'phone' into the textgrid along with their data and so on from the audio..
Example : ['phone', 'word', 'pitch', ...etc ]

For now I only know how to create an tier with nothing in it 
Example : 
phonetier = tgio.IntervalTier('phone', [ ] , 0, pairedWav=join(inputPath, fn))

The entryList stores nothing for now and I was wondering how / where to get the data to store in the entryList.

Sorry for the confusion caused.

**Comment by timmahrt** [comment]
tgio.IntervalTier('phone', [ ] , 0, pairedWav=join(inputPath, fn))

That empty list [ ] should be where you put the data.  The format is
("label", start_time, end_time).

You'll get the label, start time and end time from the forced aligner.
What does your input to praatio look like (the output of the forced
aligner)?

**Comment by timmahrt** [comment]
As in [("label1", start_time_1, end_time_1), ("label2", start_time2,
end_time2), ...]

**Comment by jiunn95** [comment]
Sorry, I'm trying out using sppas_util.py to do it instead. However I'm not sure if I'm doing it correctly. 

My code:

import os
from os.path import join
from praatio import tgio
from praatio.applied_scripts.sppas_util import sppasPostProcess

inputgrid = join('C:/Users/Desktop/work27dec/praatIO-master/praatIO-master/examples/files','generated_textgrids','mary.TextGrid')

output = join('C:/Users/Desktop/work27dec/praatIO-master/praatIO-master/examples/files','generated_textgrids2')

sppasPostProcess(inputgrid,output)
                  

Error:
  File "C:\Users\Desktop\work27dec\praatIO-master\praatIO-master\sppas.py", line 10, in <module>
    sppasPostProcess(inputgrid,output)
  File "C:\Users\Desktop\work27dec\praatIO-master\praatIO-master\praatio\applied_scripts\sppas_util.py", line 95, in sppasPostProcess
    tgFNList = utils.findFiles(tgPath, filterExt=".TextGrid")
  File "C:\Users\Desktop\work27dec\praatIO-master\praatIO-master\praatio\utilities\utils.py", line 247, in findFiles
    fnList = os.listdir(path)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:/Users/Desktop/work27dec/praatIO-master/praatIO-master/examples/files\\generated_textgrids\\mary.TextGrid'

**Comment by timmahrt** [comment]
To run sppas_util.sppasPostProcess() please see this example file:
https://github.com/timmahrt/praatIO/blob/master/examples/sppas_post_process.py

The arguments to sppasPostProcess() are folder paths, not files.

Also, instead of:

inputgrid = join('C:/Users/Desktop/work27dec/praatIO-master/
praatIO-master/examples/files','generated_textgrids','mary.TextGrid')

use (note the 'r' in front of the string):

input = r'C:/Users/Desktop/work27dec/praatIO-master/
praatIO-master/examples/files/generated_textgrids/mary.TextGrid'
